OSC++: osc::OSCException Class Reference
osc::OSCException Class Reference
Base exception class for all OSC-related errors.
#include <Exceptions.h>
Public Types
enum class ErrorCode {
None = 0 , NetworkError , MalformedPacket , TypeMismatch ,
BufferOverflow , UnknownType , AddressError , InvalidArgument ,
InvalidMessage , InvalidBundle , PatternError , ServerError ,
ClientError , OutOfMemory , NotImplemented , SocketError ,
NetworkingError , MessageTooLarge , DeserializationError , SerializationError ,
MatchError
}
Error codes for OSC exceptions.
Public Member Functions
OSCException (const std::string &message, ErrorCode code=ErrorCode::None)
Construct a new OSC Exception.
ErrorCode code () const
Get the error code.
Static Public Member Functions
static std::string getErrorDescription (ErrorCode code)
Get a description for an error code.
Private Attributes
ErrorCode code_
Detailed Description
Base exception class for all OSC-related errors.
Definition at line 15 of file Exceptions.h.
Member Enumeration Documentation
ErrorCode
enum class osc::OSCException::ErrorCode strong
Error codes for OSC exceptions.
Enumerator
None
NetworkError
Network-related error.
MalformedPacket
Packet does not conform to OSC spec.
TypeMismatch
Type tag doesn't match expected types.
BufferOverflow
Buffer size exceeded.
UnknownType
Unknown OSC type tag.
AddressError
Error with OSC address pattern.
InvalidArgument
Invalid function argument.
InvalidMessage
Invalid OSC message format.
InvalidBundle
Invalid OSC bundle format.
PatternError
OSC pattern matching error.
ServerError
Server error.
ClientError
Client error.
OutOfMemory
Out of memory error.
NotImplemented
Feature not implemented.
SocketError
Socket error.
NetworkingError
Networking subsystem error.
MessageTooLarge
Message exceeds maximum allowed size.
DeserializationError
Error during deserialization.
SerializationError
Error during serialization.
MatchError
Error during pattern matching.
Definition at line 20 of file Exceptions.h.
Constructor & Destructor Documentation
OSCException()
osc::OSCException::OSCException (const std::string & message, ErrorCode code = ErrorCode::None) inline
Construct a new OSC Exception.
Parameters
message Error message
code Error code
Definition at line 49 of file Exceptions.h.
References code(), code_, and None.
Referenced by osc::AddressException::AddressException(), osc::AddressException::AddressException(), osc::BufferOverflowException::BufferOverflowException(), osc::ClientException::ClientException(), osc::DeserializationException::DeserializationException(), osc::InvalidArgumentException::InvalidArgumentException(), osc::InvalidBundleException::InvalidBundleException(), osc::InvalidMessageException::InvalidMessageException(), osc::MalformedPacketException::MalformedPacketException(), osc::MatchException::MatchException(), osc::MessageSizeException::MessageSizeException(), osc::NetworkException::NetworkException(), osc::NetworkException::NetworkException(), osc::NetworkingException::NetworkingException(), osc::NotImplementedException::NotImplementedException(), osc::OutOfMemoryException::OutOfMemoryException(), osc::PatternException::PatternException(), osc::PlatformException::PlatformException(), osc::SerializationException::SerializationException(), osc::ServerException::ServerException(), osc::SocketException::SocketException(), osc::SocketException::SocketException(), osc::TypeMismatchException::TypeMismatchException(), and osc::UnknownTypeException::UnknownTypeException().
Member Function Documentation
code()
ErrorCode osc::OSCException::code () const inline
Get the error code.
Returns
ErrorCode
Definition at line 56 of file Exceptions.h.
References code_.
Referenced by osc::Server::addMethod(), osc::AddressException::AddressException(), osc::AddressImpl::AddressImpl(), osc::Bundle::deserialize(), getErrorDescription(), osc::initialize(), osc::NetworkException::NetworkException(), OSCException(), osc::PlatformException::PlatformException(), osc::ServerImpl::receive(), osc::ServerThread::run(), osc::Bundle::serialize(), osc::Server::Server(), osc::Server::setDefaultMethod(), osc::SocketException::SocketException(), and osc::Server::start().
getErrorDescription()
std::string osc::OSCException::getErrorDescription (ErrorCode code) static
Get a description for an error code.
Parameters
code The error code
Returns
std::string The description
Definition at line 7 of file OSCException.cpp.
References AddressError, BufferOverflow, ClientError, code(), DeserializationError, InvalidArgument, InvalidBundle, InvalidMessage, MalformedPacket, MatchError, MessageTooLarge, NetworkError, NetworkingError, None, NotImplemented, OutOfMemory, PatternError, SerializationError, ServerError, SocketError, TypeMismatch, and UnknownType.
Member Data Documentation
code_
ErrorCode osc::OSCException::code_ private
Definition at line 66 of file Exceptions.h.
Referenced by code(), and OSCException().
The documentation for this class was generated from the following files:
include/osc/Exceptions.h
src/OSCException.cpp