OSC++: osc::Blob Class Reference
osc::Blob Class Reference
Class representing an OSC Blob.
#include <Types.h>
Public Member Functions
Blob ()=default
Default constructor (empty blob)
Blob (std::vector< std::byte > data)
Construct from data.
Blob (const void *data, size_t size)
Construct from raw data.
const std::vector< std::byte > & data () const
Get the data.
size_t size () const
Get the data size.
const std::byte * bytes () const
Get pointer to raw data.
Private Attributes
std::vector< std::byte > data_
Detailed Description
Class representing an OSC Blob.
OSC Blobs are binary data with a specified size.
Definition at line 154 of file Types.h.
Constructor & Destructor Documentation
Blob() [1/3]
osc::Blob::Blob () default
Default constructor (empty blob)
Blob() [2/3]
osc::Blob::Blob (std::vector< std::byte > data) explicit
Construct from data.
Parameters
data Binary data
References data().
Blob() [3/3]
osc::Blob::Blob (const void * data, size_t size)
Construct from raw data.
Parameters
data Pointer to data
size Size of data in bytes
References data(), and size().
Member Function Documentation
bytes()
const std::byte * osc::Blob::bytes () const
Get pointer to raw data.
Returns
Const pointer to data
Referenced by osc::Value::serialize().
data()
const std::vector< std::byte > & osc::Blob::data () const
Get the data.
Returns
Reference to internal data vector
Referenced by Blob(), and Blob().
size()
size_t osc::Blob::size () const
Get the data size.
Returns
Size in bytes
Referenced by Blob(), and osc::Value::serialize().
Member Data Documentation
data_
std::vector<std::byte> osc::Blob::data_ private
Definition at line 193 of file Types.h.
The documentation for this class was generated from the following file:
include/osc/Types.h