OSC++: osc::Address Class Reference
osc::Address Class Reference
#include <Address.h>
Public Member Functions
Address (const std::string &host, const std::string &port, Protocol protocol=Protocol::UDP)
Construct an Address object with the specified host, port, and protocol.
~Address ()
Destructor - cleans up resources.
Address (const Address &other)
Copy constructor.
Address & operator= (const Address &other)
Copy assignment operator.
Address (Address &&other) noexcept
Move constructor.
Address & operator= (Address &&other) noexcept
Move assignment operator.
bool send (const std::vector< std::byte > &data)
Send raw binary data to this address.
bool send (const Message &message)
Send an OSC message to this address.
bool send (const Bundle &bundle)
Send an OSC bundle to this address.
std::string url () const
Get the URL of this address.
std::string host () const
Get the hostname.
std::string port () const
Get the port.
Protocol protocol () const
Get the protocol.
void setTTL (int ttl)
Set the TTL (Time To Live) for multicast packets.
int getTTL () const
Get the current TTL value.
void setNoDelay (bool enable)
Enable or disable TCP_NODELAY (Nagle's algorithm)
void setTimeout (std::chrono::milliseconds timeout)
Set socket timeout.
bool isValid () const
Check if the address is valid and can be used.
int getErrorCode () const
Get the last error code from socket operations.
std::string getErrorMessage () const
Get the error message for the last error.
Static Public Member Functions
static Address fromUrl (const std::string &url)
Create an Address from a URL string.
Private Attributes
AddressImpl * impl_
Detailed Description
Definition at line 24 of file Address.h.
Constructor & Destructor Documentation
Address() [1/3]
osc::Address::Address (const std::string & host, const std::string & port, Protocol protocol = Protocol::UDP)
Construct an Address object with the specified host, port, and protocol.
Parameters
host Hostname or IP address.
port Port number or service name.
protocol Transport protocol (UDP, TCP, UNIX).
Definition at line 14 of file Address.cpp.
References host(), impl_, port(), and protocol().
Referenced by Address(), Address(), fromUrl(), operator=(), and operator=().
~Address()
osc::Address::~Address ()
Destructor - cleans up resources.
Definition at line 61 of file Address.cpp.
References impl_.
Address() [2/3]
osc::Address::Address (const Address & other)
Copy constructor.
Definition at line 76 of file Address.cpp.
References Address(), osc::AddressImpl::getTTL(), host(), impl_, port(), and protocol().
Address() [3/3]
osc::Address::Address (Address && other) noexcept
Move constructor.
Definition at line 64 of file Address.cpp.
References Address(), and impl_.
Member Function Documentation
fromUrl()
Address osc::Address::fromUrl (const std::string & url) static
Create an Address from a URL string.
Parameters
url URL in format "osc.proto://host:port/"
Returns
A new Address instance
Exceptions
OSCException if the URL format is invalid
Definition at line 18 of file Address.cpp.
References Address(), osc::OSCException::AddressError, host(), port(), protocol(), osc::TCP, osc::UDP, osc::UNIX, and url().
getErrorCode()
int osc::Address::getErrorCode () const
Get the last error code from socket operations.
Returns
Platform-specific error code.
Definition at line 158 of file Address.cpp.
References impl_.
getErrorMessage()
std::string osc::Address::getErrorMessage () const
Get the error message for the last error.
Returns
Error message string.
Definition at line 160 of file Address.cpp.
References impl_.
getTTL()
int osc::Address::getTTL () const
Get the current TTL value.
Returns
Current TTL value
Definition at line 175 of file Address.cpp.
References impl_.
host()
std::string osc::Address::host () const
Get the hostname.
Returns
The hostname or IP address
Definition at line 198 of file Address.cpp.
References impl_.
Referenced by Address(), Address(), and fromUrl().
isValid()
bool osc::Address::isValid () const
Check if the address is valid and can be used.
Returns
true if valid, false otherwise.
Definition at line 156 of file Address.cpp.
References impl_.
operator=() [1/2]
Address & osc::Address::operator= (Address && other) noexcept
Move assignment operator.
Definition at line 66 of file Address.cpp.
References Address(), and impl_.
operator=() [2/2]
Address & osc::Address::operator= (const Address & other)
Copy assignment operator.
Definition at line 85 of file Address.cpp.
References Address(), osc::AddressImpl::getTTL(), osc::AddressImpl::host(), impl_, osc::AddressImpl::port(), osc::AddressImpl::protocol(), and osc::AddressImpl::setTTL().
port()
std::string osc::Address::port () const
Get the port.
Returns
The port or service name
Definition at line 200 of file Address.cpp.
References impl_.
Referenced by Address(), Address(), and fromUrl().
protocol()
Protocol osc::Address::protocol () const
Get the protocol.
Returns
The transport protocol
Definition at line 202 of file Address.cpp.
References impl_, and osc::UDP.
Referenced by Address(), Address(), and fromUrl().
send() [1/3]
bool osc::Address::send (const Bundle & bundle)
Send an OSC bundle to this address.
Parameters
bundle The bundle to send.
Returns
true if successful, false on error.
Exceptions
OSCException on network errors
Definition at line 135 of file Address.cpp.
References impl_, osc::OSCException::NetworkError, and osc::Bundle::serialize().
send() [2/3]
bool osc::Address::send (const Message & message)
Send an OSC message to this address.
Parameters
message The message to send.
Returns
true if successful, false on error.
Exceptions
OSCException on network errors
Definition at line 118 of file Address.cpp.
References impl_, osc::OSCException::NetworkError, and osc::Message::serialize().
send() [3/3]
bool osc::Address::send (const std::vector< std::byte > & data)
Send raw binary data to this address.
Parameters
data The data buffer to send.
Returns
true if successful, false on error.
Exceptions
OSCException on network errors
Definition at line 102 of file Address.cpp.
References impl_, and osc::OSCException::NetworkError.
setNoDelay()
void osc::Address::setNoDelay (bool enable)
Enable or disable TCP_NODELAY (Nagle's algorithm)
Parameters
enable true to disable Nagle's algorithm
Note
Only applies to TCP protocol
Definition at line 177 of file Address.cpp.
References impl_.
setTimeout()
void osc::Address::setTimeout (std::chrono::milliseconds timeout)
Set socket timeout.
Parameters
timeout Timeout duration in milliseconds
Definition at line 187 of file Address.cpp.
References impl_.
setTTL()
void osc::Address::setTTL (int ttl)
Set the TTL (Time To Live) for multicast packets.
Parameters
ttl TTL value (1-255)
Note
Only applies to UDP protocol
Definition at line 165 of file Address.cpp.
References impl_.
url()
std::string osc::Address::url () const
Get the URL of this address.
Returns
URL in format "osc.proto://host:port/".
Definition at line 153 of file Address.cpp.
References impl_.
Referenced by fromUrl().
Member Data Documentation
impl_
AddressImpl* osc::Address::impl_ private
Definition at line 161 of file Address.h.
Referenced by Address(), Address(), Address(), getErrorCode(), getErrorMessage(), getTTL(), host(), isValid(), operator=(), operator=(), port(), protocol(), send(), send(), send(), setNoDelay(), setTimeout(), setTTL(), url(), and ~Address().
The documentation for this class was generated from the following files:
include/osc/Address.h
src/Address.cpp