OSC++: osc::ServerImpl Class Reference
osc::ServerImpl Class Reference
#include <ServerImpl.h>
Public Member Functions
ServerImpl (std::string port, Protocol protocol)
~ServerImpl ()
MethodId addMethod (const std::string &pathPattern, const std::string &typeSpec, MethodHandler handler)
MethodId addDefaultMethod (MethodHandler handler)
bool removeMethod (MethodId id)
void setBundleHandlers (BundleStartHandler startHandler, BundleEndHandler endHandler)
void setErrorHandler (ErrorHandler handler)
bool wait (std::chrono::milliseconds timeout)
bool receive (std::chrono::milliseconds timeout)
bool hasPendingMessages () const
int port () const
std::string url () const
Private Member Functions
void cleanup ()
bool initializeSocket ()
bool resolveAddress ()
void dispatchMessage (const Message &message)
void dispatchBundle (const Bundle &bundle)
bool matchMethod (const std::string &path, const std::string &types, std::vector< Method * > &matchedMethods)
std::regex convertPathToRegex (const std::string &pattern)
Static Private Member Functions
static bool initializeNetworking ()
static void cleanupNetworking ()
static int getLastSocketError ()
static bool matchPattern (const std::string &pattern, const std::string &path)
Private Attributes
std::string port_
Protocol protocol_
SOCKET_TYPE socket_
std::map< MethodId, Method > methods_
MethodId nextMethodId_
std::mutex methodMutex_
BundleStartHandler bundleStartHandler_
BundleEndHandler bundleEndHandler_
ErrorHandler errorHandler_
size_t maxMessageSize_
Static Private Attributes
static bool networkingInitialized = false
Detailed Description
Definition at line 37 of file ServerImpl.h.
Constructor & Destructor Documentation
ServerImpl()
osc::ServerImpl::ServerImpl (std::string port, Protocol protocol)
Definition at line 32 of file ServerImpl.cpp.
References bundleEndHandler_, bundleStartHandler_, errorHandler_, getLastSocketError(), initializeNetworking(), initializeSocket(), INVALID_SOCKET_VALUE, maxMessageSize_, osc::OSCException::NetworkingError, networkingInitialized, nextMethodId_, port(), port_, protocol_, socket_, and osc::OSCException::SocketError.
~ServerImpl()
osc::ServerImpl::~ServerImpl ()
Definition at line 67 of file ServerImpl.cpp.
References cleanup().
Member Function Documentation
addDefaultMethod()
MethodId osc::ServerImpl::addDefaultMethod (MethodHandler handler)
Definition at line 100 of file ServerImpl.cpp.
References osc::Method::handler, osc::Method::id, osc::Method::isDefault, methodMutex_, methods_, nextMethodId_, osc::Method::pathPattern, and osc::Method::typeSpec.
addMethod()
MethodId osc::ServerImpl::addMethod (const std::string & pathPattern, const std::string & typeSpec, MethodHandler handler)
Definition at line 70 of file ServerImpl.cpp.
References convertPathToRegex(), osc::Method::handler, osc::Method::id, osc::Method::isDefault, methodMutex_, methods_, nextMethodId_, osc::Method::pathPattern, osc::Method::pathRegex, osc::OSCException::PatternError, and osc::Method::typeSpec.
cleanup()
void osc::ServerImpl::cleanup () private
Definition at line 394 of file ServerImpl.cpp.
References CLOSE_SOCKET, INVALID_SOCKET_VALUE, port_, protocol_, socket_, and osc::UNIX.
Referenced by initializeSocket(), and ~ServerImpl().
cleanupNetworking()
void osc::ServerImpl::cleanupNetworking () static private
Definition at line 424 of file ServerImpl.cpp.
References networkingInitialized.
convertPathToRegex()
std::regex osc::ServerImpl::convertPathToRegex (const std::string & pattern) private
Definition at line 521 of file ServerImpl.cpp.
References osc::OSCException::PatternError.
Referenced by addMethod().
dispatchBundle()
void osc::ServerImpl::dispatchBundle (const Bundle & bundle) private
Definition at line 489 of file ServerImpl.cpp.
References bundleEndHandler_, bundleStartHandler_, dispatchMessage(), errorHandler_, and osc::Bundle::messages().
Referenced by receive().
dispatchMessage()
void osc::ServerImpl::dispatchMessage (const Message & message) private
Definition at line 441 of file ServerImpl.cpp.
References errorHandler_, osc::Message::getArguments(), osc::Message::getPath(), matchMethod(), methodMutex_, and methods_.
Referenced by dispatchBundle(), and receive().
getLastSocketError()
int osc::ServerImpl::getLastSocketError () static private
Definition at line 432 of file ServerImpl.cpp.
Referenced by initializeSocket(), receive(), ServerImpl(), and wait().
hasPendingMessages()
bool osc::ServerImpl::hasPendingMessages () const
Definition at line 272 of file ServerImpl.cpp.
References socket_.
initializeNetworking()
bool osc::ServerImpl::initializeNetworking () static private
Definition at line 409 of file ServerImpl.cpp.
References networkingInitialized.
Referenced by ServerImpl().
initializeSocket()
bool osc::ServerImpl::initializeSocket () private
Definition at line 287 of file ServerImpl.cpp.
References cleanup(), errorHandler_, getLastSocketError(), INVALID_SOCKET_VALUE, port_, protocol_, socket_, osc::TCP, osc::UDP, and osc::UNIX.
Referenced by ServerImpl().
matchMethod()
bool osc::ServerImpl::matchMethod (const std::string & path, const std::string & types, std::vector< Method * > & matchedMethods) private
Definition at line 592 of file ServerImpl.cpp.
References errorHandler_, osc::Method::isDefault, osc::OSCException::MatchError, matchPattern(), methods_, osc::Method::pathPattern, osc::OSCException::TypeMismatch, and osc::Method::typeSpec.
Referenced by dispatchMessage().
matchPattern()
bool osc::ServerImpl::matchPattern (const std::string & pattern, const std::string & path) static private
Definition at line 786 of file ServerImpl.cpp.
References matchPattern().
Referenced by matchMethod(), and matchPattern().
port()
int osc::ServerImpl::port () const
Definition at line 251 of file ServerImpl.cpp.
References port_.
Referenced by ServerImpl().
receive()
bool osc::ServerImpl::receive (std::chrono::milliseconds timeout)
Definition at line 175 of file ServerImpl.cpp.
References osc::OSCException::code(), osc::Bundle::deserialize(), osc::Message::deserialize(), dispatchBundle(), dispatchMessage(), errorHandler_, getLastSocketError(), INVALID_SOCKET_VALUE, maxMessageSize_, protocol_, osc::tcp_framing::receiveFramed(), socket_, osc::TCP, osc::UDP, osc::UNIX, and wait().
removeMethod()
bool osc::ServerImpl::removeMethod (MethodId id)
Definition at line 121 of file ServerImpl.cpp.
References methodMutex_, and methods_.
resolveAddress()
bool osc::ServerImpl::resolveAddress () private
setBundleHandlers()
void osc::ServerImpl::setBundleHandlers (BundleStartHandler startHandler, BundleEndHandler endHandler)
Definition at line 135 of file ServerImpl.cpp.
References bundleEndHandler_, and bundleStartHandler_.
setErrorHandler()
void osc::ServerImpl::setErrorHandler (ErrorHandler handler)
Definition at line 142 of file ServerImpl.cpp.
References errorHandler_.
url()
std::string osc::ServerImpl::url () const
Definition at line 254 of file ServerImpl.cpp.
References port_, protocol_, osc::TCP, osc::UDP, and osc::UNIX.
wait()
bool osc::ServerImpl::wait (std::chrono::milliseconds timeout)
Definition at line 145 of file ServerImpl.cpp.
References errorHandler_, getLastSocketError(), INVALID_SOCKET_VALUE, socket_, and SOCKET_ERROR_VALUE.
Referenced by receive().
Member Data Documentation
bundleEndHandler_
BundleEndHandler osc::ServerImpl::bundleEndHandler_ private
Definition at line 76 of file ServerImpl.h.
Referenced by dispatchBundle(), ServerImpl(), and setBundleHandlers().
bundleStartHandler_
BundleStartHandler osc::ServerImpl::bundleStartHandler_ private
Definition at line 75 of file ServerImpl.h.
Referenced by dispatchBundle(), ServerImpl(), and setBundleHandlers().
errorHandler_
ErrorHandler osc::ServerImpl::errorHandler_ private
Definition at line 77 of file ServerImpl.h.
Referenced by dispatchBundle(), dispatchMessage(), initializeSocket(), matchMethod(), receive(), ServerImpl(), setErrorHandler(), and wait().
maxMessageSize_
size_t osc::ServerImpl::maxMessageSize_ private
Definition at line 78 of file ServerImpl.h.
Referenced by receive(), and ServerImpl().
methodMutex_
std::mutex osc::ServerImpl::methodMutex_ private
Definition at line 74 of file ServerImpl.h.
Referenced by addDefaultMethod(), addMethod(), dispatchMessage(), and removeMethod().
methods_
std::map<MethodId, Method> osc::ServerImpl::methods_ private
Definition at line 72 of file ServerImpl.h.
Referenced by addDefaultMethod(), addMethod(), dispatchMessage(), matchMethod(), and removeMethod().
networkingInitialized
bool osc::ServerImpl::networkingInitialized = false static private
Definition at line 79 of file ServerImpl.h.
Referenced by cleanupNetworking(), initializeNetworking(), and ServerImpl().
nextMethodId_
MethodId osc::ServerImpl::nextMethodId_ private
Definition at line 73 of file ServerImpl.h.
Referenced by addDefaultMethod(), addMethod(), and ServerImpl().
port_
std::string osc::ServerImpl::port_ private
Definition at line 69 of file ServerImpl.h.
Referenced by cleanup(), initializeSocket(), port(), ServerImpl(), and url().
protocol_
Protocol osc::ServerImpl::protocol_ private
Definition at line 70 of file ServerImpl.h.
Referenced by cleanup(), initializeSocket(), receive(), ServerImpl(), and url().
socket_
SOCKET_TYPE osc::ServerImpl::socket_ private
Definition at line 71 of file ServerImpl.h.
Referenced by cleanup(), hasPendingMessages(), initializeSocket(), receive(), ServerImpl(), and wait().
The documentation for this class was generated from the following files:
include/osc/ServerImpl.h
src/ServerImpl.cpp