OSC++: osc::Server Class Reference
osc::Server Class Reference
The Server class handles incoming OSC messages.
#include <Server.h>
Public Member Functions
Server (const std::string &port, Protocol protocol)
Construct a new Server object.
~Server ()
Destructor.
bool start ()
Start the server.
void stop ()
Stop the server.
bool receive (std::chrono::milliseconds timeout=std::chrono::milliseconds(0))
Receive and process pending OSC messages.
bool hasPendingMessages () const
Check if there are pending messages to be processed.
MethodId addMethod (const std::string &pathPattern, const std::string &typeSpec, std::function< void(const Message &)> handler)
Add a method handler for a specific OSC address.
void setDefaultMethod (std::function< void(const Message &)> handler)
Set a default handler for unhandled messages.
void setErrorHandler (std::function< void(int, const std::string &)> handler)
Set an error handler for the server.
Private Attributes
std::unique_ptr< ServerImpl > impl_
Detailed Description
The Server class handles incoming OSC messages.
Definition at line 24 of file Server.h.
Constructor & Destructor Documentation
Server()
osc::Server::Server (const std::string & port, Protocol protocol)
Construct a new Server object.
Parameters
port The port number to listen on
protocol The transport protocol (UDP, TCP, etc.)
Definition at line 10 of file Server.cpp.
References osc::OSCException::code(), impl_, and osc::OSCException::ServerError.
~Server()
osc::Server::~Server () default
Destructor.
Member Function Documentation
addMethod()
MethodId osc::Server::addMethod (const std::string & pathPattern, const std::string & typeSpec, std::function< void(const Message &)> handler)
Add a method handler for a specific OSC address.
Parameters
pathPattern The OSC address pattern
typeSpec The expected argument types
handler The function to handle incoming messages
Returns
MethodId The ID of the registered method
Definition at line 70 of file Server.cpp.
References osc::OSCException::code(), impl_, and osc::OSCException::ServerError.
hasPendingMessages()
bool osc::Server::hasPendingMessages () const
Check if there are pending messages to be processed.
Returns
true if there are pending messages, false otherwise
Definition at line 64 of file Server.cpp.
References impl_.
receive()
bool osc::Server::receive (std::chrono::milliseconds timeout = std::chrono::milliseconds(0))
Receive and process pending OSC messages.
Parameters
timeout The maximum time to wait for messages in milliseconds (default: 0)
Returns
true if messages were received and processed, false otherwise
Definition at line 58 of file Server.cpp.
References impl_.
setDefaultMethod()
void osc::Server::setDefaultMethod (std::function< void(const Message &)> handler)
Set a default handler for unhandled messages.
Parameters
handler The function to handle unhandled messages
Definition at line 90 of file Server.cpp.
References osc::OSCException::code(), impl_, and osc::OSCException::ServerError.
setErrorHandler()
void osc::Server::setErrorHandler (std::function< void(int, const std::string &)> handler)
Set an error handler for the server.
Parameters
handler The function to handle errors
Definition at line 108 of file Server.cpp.
References impl_, and osc::OSCException::ServerError.
start()
bool osc::Server::start ()
Start the server.
Returns
true if the server started successfully, false otherwise
Definition at line 28 of file Server.cpp.
References osc::OSCException::code(), and impl_.
stop()
void osc::Server::stop ()
Stop the server.
Definition at line 52 of file Server.cpp.
Member Data Documentation
impl_
std::unique_ptr<ServerImpl> osc::Server::impl_ private
Definition at line 85 of file Server.h.
Referenced by addMethod(), hasPendingMessages(), receive(), Server(), setDefaultMethod(), setErrorHandler(), and start().
The documentation for this class was generated from the following files:
include/osc/Server.h
src/Server.cpp