OSC++: osc::AddressImpl Class Reference
osc::AddressImpl Class Reference
#include <AddressImpl.h>
Public Member Functions
AddressImpl (std::string host, std::string port, Protocol protocol)
Construct a new Address Implementation object.
~AddressImpl ()
Destroy the Address Implementation object.
bool send (const std::vector< std::byte > &data)
Send data to the address.
std::string url () const
Get the URL representation of this address.
std::string host () const
Get the hostname.
std::string port () const
Get the port.
Protocol protocol () const
Get the protocol.
bool setTTL (int ttl)
Set the Time To Live for multicast.
int getTTL () const
Get the Time To Live for multicast.
bool setNoDelay (bool enable)
Set the No Delay option for TCP.
bool setTimeout (std::chrono::milliseconds timeout)
Set the socket timeout.
bool isValid () const
Check if the socket is valid.
Private Member Functions
bool initializeSocket ()
Initialize the socket.
bool resolveAddress ()
Resolve the address.
void cleanup ()
Clean up resources.
std::string getSystemErrorMessage () const
Get the system error code and convert to a string message.
int getSystemErrorCode () const
Get the system error code.
Static Private Member Functions
static bool initializeNetworking ()
Initialize the networking subsystem.
static void cleanupNetworking ()
Clean up the networking subsystem.
Private Attributes
std::string host_
std::string port_
Protocol protocol_
SOCKET_TYPE socket_ = INVALID_SOCKET_VALUE
int ttl_ = 1
bool connected_ = false
struct addrinfo * addrInfo_ = nullptr
Static Private Attributes
static bool networkingInitialized = false
Flag indicating if networking has been initialized.
Detailed Description
Definition at line 44 of file AddressImpl.h.
Constructor & Destructor Documentation
AddressImpl()
osc::AddressImpl::AddressImpl (std::string host, std::string port, Protocol protocol)
Construct a new Address Implementation object.
Parameters
host The hostname or IP address to connect to
port The port to connect to
protocol The transport protocol to use
Exceptions
OSCException if the address cannot be resolved or the socket cannot be created
Definition at line 61 of file AddressImpl.cpp.
References osc::OSCException::AddressError, cleanup(), osc::OSCException::code(), getSystemErrorMessage(), host(), host_, initializeNetworking(), initializeSocket(), networkingInitialized, port(), port_, protocol(), protocol_, resolveAddress(), and osc::OSCException::SocketError.
~AddressImpl()
osc::AddressImpl::~AddressImpl ()
Destroy the Address Implementation object.
Definition at line 105 of file AddressImpl.cpp.
References cleanup().
Member Function Documentation
cleanup()
void osc::AddressImpl::cleanup () private
Clean up resources.
Definition at line 108 of file AddressImpl.cpp.
References addrInfo_, CLOSE_SOCKET, INVALID_SOCKET_VALUE, and socket_.
Referenced by AddressImpl(), and ~AddressImpl().
cleanupNetworking()
void osc::AddressImpl::cleanupNetworking () static private
Clean up the networking subsystem.
Definition at line 52 of file AddressImpl.cpp.
References networkingInitialized.
Referenced by osc::cleanup().
getSystemErrorCode()
int osc::AddressImpl::getSystemErrorCode () const private
Get the system error code.
Returns
int The error code
Definition at line 399 of file AddressImpl.cpp.
getSystemErrorMessage()
std::string osc::AddressImpl::getSystemErrorMessage () const private
Get the system error code and convert to a string message.
Returns
std::string The error message
Definition at line 380 of file AddressImpl.cpp.
Referenced by AddressImpl(), send(), setNoDelay(), setTimeout(), and setTTL().
getTTL()
int osc::AddressImpl::getTTL () const inline
Get the Time To Live for multicast.
Returns
int The TTL value
Definition at line 112 of file AddressImpl.h.
References ttl_.
Referenced by osc::Address::Address(), and osc::Address::operator=().
host()
std::string osc::AddressImpl::host () const inline
Get the hostname.
Returns
std::string The hostname
Definition at line 82 of file AddressImpl.h.
References host_.
Referenced by AddressImpl(), and osc::Address::operator=().
initializeNetworking()
bool osc::AddressImpl::initializeNetworking () static private
Initialize the networking subsystem.
Returns
true if successful
Exceptions
OSCException if the networking subsystem cannot be initialized
Definition at line 36 of file AddressImpl.cpp.
References osc::OSCException::NetworkingError, and networkingInitialized.
Referenced by AddressImpl(), and osc::initialize().
initializeSocket()
bool osc::AddressImpl::initializeSocket () private
Initialize the socket.
Returns
true if successful
Exceptions
OSCException if the socket cannot be created
Definition at line 121 of file AddressImpl.cpp.
References addrInfo_, INVALID_SOCKET_VALUE, and socket_.
Referenced by AddressImpl().
isValid()
bool osc::AddressImpl::isValid () const inline
Check if the socket is valid.
Returns
true if the socket is valid
Definition at line 137 of file AddressImpl.h.
References INVALID_SOCKET_VALUE, and socket_.
port()
std::string osc::AddressImpl::port () const inline
Get the port.
Returns
std::string The port
Definition at line 89 of file AddressImpl.h.
References port_.
Referenced by AddressImpl(), and osc::Address::operator=().
protocol()
Protocol osc::AddressImpl::protocol () const inline
Get the protocol.
Returns
Protocol The protocol
Definition at line 96 of file AddressImpl.h.
References protocol_.
Referenced by AddressImpl(), and osc::Address::operator=().
resolveAddress()
bool osc::AddressImpl::resolveAddress () private
Resolve the address.
Returns
true if successful
Exceptions
OSCException if the address cannot be resolved
Definition at line 146 of file AddressImpl.cpp.
References osc::OSCException::AddressError, addrInfo_, host_, osc::OSCException::NotImplemented, port_, protocol_, osc::TCP, osc::UDP, and osc::UNIX.
Referenced by AddressImpl().
send()
bool osc::AddressImpl::send (const std::vector< std::byte > & data)
Send data to the address.
Parameters
data The data to send
Returns
true if the data was sent successfully
Exceptions
OSCException if the data cannot be sent
Definition at line 190 of file AddressImpl.cpp.
References addrInfo_, connected_, getSystemErrorMessage(), host_, INVALID_SOCKET_VALUE, osc::MAX_MESSAGE_SIZE, osc::OSCException::MessageTooLarge, osc::OSCException::NetworkError, osc::OSCException::NotImplemented, port_, protocol_, send(), osc::OSCException::SerializationError, socket_, SOCKET_ERROR_VALUE, osc::OSCException::SocketError, osc::TCP, osc::UDP, and osc::UNIX.
Referenced by send().
setNoDelay()
bool osc::AddressImpl::setNoDelay (bool enable)
Set the No Delay option for TCP.
Parameters
enable Whether to enable or disable Nagle's algorithm
Returns
true if successful
Exceptions
OSCException if the option cannot be set
Definition at line 338 of file AddressImpl.cpp.
References getSystemErrorMessage(), INVALID_SOCKET_VALUE, osc::OSCException::InvalidArgument, osc::OSCException::NetworkError, protocol_, socket_, SOCKET_ERROR_VALUE, and osc::TCP.
setTimeout()
bool osc::AddressImpl::setTimeout (std::chrono::milliseconds timeout)
Set the socket timeout.
Parameters
timeout The timeout value
Returns
true if successful
Exceptions
OSCException if the timeout cannot be set
Definition at line 358 of file AddressImpl.cpp.
References getSystemErrorMessage(), INVALID_SOCKET_VALUE, osc::OSCException::NetworkError, socket_, SOCKET_ERROR_VALUE, and osc::OSCException::SocketError.
setTTL()
bool osc::AddressImpl::setTTL (int ttl)
Set the Time To Live for multicast.
Parameters
ttl The TTL value (1-255)
Returns
true if successful
Exceptions
OSCException if the TTL cannot be set
Definition at line 315 of file AddressImpl.cpp.
References getSystemErrorMessage(), INVALID_SOCKET_VALUE, osc::OSCException::InvalidArgument, osc::OSCException::NetworkError, protocol_, socket_, SOCKET_ERROR_VALUE, ttl_, and osc::UDP.
Referenced by osc::Address::operator=().
url()
std::string osc::AddressImpl::url () const
Get the URL representation of this address.
Returns
std::string The URL
Definition at line 286 of file AddressImpl.cpp.
References host_, port_, protocol_, osc::TCP, osc::UDP, osc::UNIX, and url().
Referenced by url().
Member Data Documentation
addrInfo_
struct addrinfo* osc::AddressImpl::addrInfo_ = nullptr private
Definition at line 146 of file AddressImpl.h.
Referenced by cleanup(), initializeSocket(), resolveAddress(), and send().
connected_
bool osc::AddressImpl::connected_ = false private
Definition at line 145 of file AddressImpl.h.
Referenced by send().
host_
std::string osc::AddressImpl::host_ private
Definition at line 140 of file AddressImpl.h.
Referenced by AddressImpl(), host(), resolveAddress(), send(), and url().
networkingInitialized
bool osc::AddressImpl::networkingInitialized = false static private
Flag indicating if networking has been initialized.
Definition at line 185 of file AddressImpl.h.
Referenced by AddressImpl(), cleanupNetworking(), and initializeNetworking().
port_
std::string osc::AddressImpl::port_ private
Definition at line 141 of file AddressImpl.h.
Referenced by AddressImpl(), port(), resolveAddress(), send(), and url().
protocol_
Protocol osc::AddressImpl::protocol_ private
Definition at line 142 of file AddressImpl.h.
Referenced by AddressImpl(), protocol(), resolveAddress(), send(), setNoDelay(), setTTL(), and url().
socket_
SOCKET_TYPE osc::AddressImpl::socket_ = INVALID_SOCKET_VALUE private
Definition at line 143 of file AddressImpl.h.
Referenced by cleanup(), initializeSocket(), isValid(), send(), setNoDelay(), setTimeout(), and setTTL().
ttl_
int osc::AddressImpl::ttl_ = 1 private
Definition at line 144 of file AddressImpl.h.
Referenced by getTTL(), and setTTL().
The documentation for this class was generated from the following files:
include/osc/AddressImpl.h
src/AddressImpl.cpp