OSC++: osc::TimeTag Class Reference
osc::TimeTag Class Reference
Class representing an OSC Time Tag.
#include <TimeTag.h>
Public Member Functions
TimeTag ()
TimeTag (uint64_t ntp)
TimeTag (uint32_t seconds, uint32_t fraction)
TimeTag (std::chrono::system_clock::time_point tp)
uint64_t toNTP () const
std::chrono::system_clock::time_point toTimePoint () const
uint32_t seconds () const
uint32_t fraction () const
bool isImmediate () const
bool operator== (const TimeTag &other) const
bool operator!= (const TimeTag &other) const
bool operator< (const TimeTag &other) const
bool operator> (const TimeTag &other) const
bool operator<= (const TimeTag &other) const
bool operator>= (const TimeTag &other) const
TimeTag ()
Default constructor (creates an immediate time tag)
TimeTag (uint64_t ntp)
Construct from NTP format (64-bit)
TimeTag (uint32_t seconds, uint32_t fraction)
Construct from seconds and fraction.
TimeTag (std::chrono::system_clock::time_point tp)
Construct from std::chrono::system_clock::time_point.
uint64_t toNTP () const
Convert to NTP format.
std::chrono::system_clock::time_point toTimePoint () const
Convert to std::chrono::system_clock::time_point.
uint32_t seconds () const
Get seconds part of time tag.
uint32_t fraction () const
Get fraction part of time tag.
bool isImmediate () const
Check if this is an immediate time tag.
bool operator== (const TimeTag &other) const
bool operator!= (const TimeTag &other) const
bool operator< (const TimeTag &other) const
bool operator> (const TimeTag &other) const
bool operator<= (const TimeTag &other) const
bool operator>= (const TimeTag &other) const
Static Public Member Functions
static TimeTag now ()
static TimeTag immediate ()
static TimeTag now ()
Get current time as TimeTag.
static TimeTag immediate ()
Get immediate execution time tag (special value)
Private Attributes
uint32_t seconds_
Seconds since Jan 1, 1900.
uint32_t fraction_
Fractional seconds (0-0xFFFFFFFF)
Detailed Description
Class representing an OSC Time Tag.
TimeTag class for handling OSC time tags. OSC time tags are represented in NTP format with seconds since 1900 and fractional seconds.
OSC Time Tags are 64-bit fixed-point numbers representing time in NTP format (seconds since Jan 1, 1900).
Definition at line 13 of file TimeTag.h.
Constructor & Destructor Documentation
TimeTag() [1/8]
osc::TimeTag::TimeTag ()
Definition at line 19 of file TimeTag.cpp.
References fraction_, and seconds_.
Referenced by immediate(), now(), operator!=(), operator<(), operator<=(), operator==(), operator>(), and operator>=().
TimeTag() [2/8]
osc::TimeTag::TimeTag (uint64_t ntp) explicit
Definition at line 22 of file TimeTag.cpp.
References fraction_, and seconds_.
TimeTag() [3/8]
osc::TimeTag::TimeTag (uint32_t seconds, uint32_t fraction)
Definition at line 26 of file TimeTag.cpp.
References fraction(), fraction_, seconds(), and seconds_.
TimeTag() [4/8]
osc::TimeTag::TimeTag (std::chrono::system_clock::time_point tp) explicit
Definition at line 30 of file TimeTag.cpp.
References fraction_, seconds(), and seconds_.
TimeTag() [5/8]
osc::TimeTag::TimeTag ()
Default constructor (creates an immediate time tag)
TimeTag() [6/8]
osc::TimeTag::TimeTag (uint64_t ntp) explicit
Construct from NTP format (64-bit)
Parameters
ntp NTP timestamp
TimeTag() [7/8]
osc::TimeTag::TimeTag (uint32_t seconds, uint32_t fraction)
Construct from seconds and fraction.
Parameters
seconds Seconds since Jan 1, 1900
fraction Fractional seconds (0-0xFFFFFFFF)
References fraction(), and seconds().
TimeTag() [8/8]
osc::TimeTag::TimeTag (std::chrono::system_clock::time_point tp) explicit
Construct from std::chrono::system_clock::time_point.
Parameters
tp Time point
Member Function Documentation
fraction() [1/2]
uint32_t osc::TimeTag::fraction () const
Definition at line 59 of file TimeTag.cpp.
References fraction_.
Referenced by TimeTag().
fraction() [2/2]
uint32_t osc::TimeTag::fraction () const
Get fraction part of time tag.
Returns
Fraction in NTP format
immediate() [1/2]
TimeTag osc::TimeTag::immediate () static
Definition at line 42 of file TimeTag.cpp.
References TimeTag().
Referenced by osc::createBundle().
immediate() [2/2]
static TimeTag osc::TimeTag::immediate () static
Get immediate execution time tag (special value)
Returns
TimeTag for immediate execution
References TimeTag().
isImmediate() [1/2]
bool osc::TimeTag::isImmediate () const
Definition at line 62 of file TimeTag.cpp.
References fraction_, and seconds_.
isImmediate() [2/2]
bool osc::TimeTag::isImmediate () const
Check if this is an immediate time tag.
Returns
true if immediate, false otherwise
now() [1/2]
TimeTag osc::TimeTag::now () static
Definition at line 39 of file TimeTag.cpp.
References TimeTag().
now() [2/2]
static TimeTag osc::TimeTag::now () static
Get current time as TimeTag.
Returns
TimeTag for current time
References TimeTag().
operator!=() [1/2]
bool osc::TimeTag::operator!= (const TimeTag & other) const
Definition at line 69 of file TimeTag.cpp.
References TimeTag().
operator!=() [2/2]
bool osc::TimeTag::operator!= (const TimeTag & other) const
References TimeTag().
operator<() [1/2]
bool osc::TimeTag::operator< (const TimeTag & other) const
Definition at line 71 of file TimeTag.cpp.
References fraction_, seconds_, and TimeTag().
operator<() [2/2]
bool osc::TimeTag::operator< (const TimeTag & other) const
References TimeTag().
operator<=() [1/2]
bool osc::TimeTag::operator<= (const TimeTag & other) const
Definition at line 78 of file TimeTag.cpp.
References TimeTag().
operator<=() [2/2]
bool osc::TimeTag::operator<= (const TimeTag & other) const
References TimeTag().
operator==() [1/2]
bool osc::TimeTag::operator== (const TimeTag & other) const
Definition at line 65 of file TimeTag.cpp.
References fraction_, seconds_, and TimeTag().
operator==() [2/2]
bool osc::TimeTag::operator== (const TimeTag & other) const
References TimeTag().
operator>() [1/2]
bool osc::TimeTag::operator> (const TimeTag & other) const
Definition at line 76 of file TimeTag.cpp.
References TimeTag().
operator>() [2/2]
bool osc::TimeTag::operator> (const TimeTag & other) const
References TimeTag().
operator>=() [1/2]
bool osc::TimeTag::operator>= (const TimeTag & other) const
Definition at line 80 of file TimeTag.cpp.
References TimeTag().
operator>=() [2/2]
bool osc::TimeTag::operator>= (const TimeTag & other) const
References fraction_, seconds_, and TimeTag().
seconds() [1/2]
uint32_t osc::TimeTag::seconds () const
Definition at line 56 of file TimeTag.cpp.
References seconds_.
Referenced by TimeTag(), and TimeTag().
seconds() [2/2]
uint32_t osc::TimeTag::seconds () const
Get seconds part of time tag.
Returns
Seconds since Jan 1, 1900
toNTP() [1/2]
uint64_t osc::TimeTag::toNTP () const
Definition at line 45 of file TimeTag.cpp.
References fraction_, and seconds_.
Referenced by osc::Value::serialize().
toNTP() [2/2]
uint64_t osc::TimeTag::toNTP () const
Convert to NTP format.
Returns
64-bit NTP timestamp
toTimePoint() [1/2]
std::chrono::system_clock::time_point osc::TimeTag::toTimePoint () const
Definition at line 48 of file TimeTag.cpp.
References fraction_, and seconds_.
toTimePoint() [2/2]
std::chrono::system_clock::time_point osc::TimeTag::toTimePoint () const
Convert to std::chrono::system_clock::time_point.
Returns
Time point
Member Data Documentation
fraction_
uint32_t osc::TimeTag::fraction_ private
Fractional seconds (0-0xFFFFFFFF)
Definition at line 59 of file TimeTag.h.
Referenced by fraction(), isImmediate(), operator<(), operator==(), operator>=(), TimeTag(), TimeTag(), TimeTag(), TimeTag(), toNTP(), and toTimePoint().
seconds_
uint32_t osc::TimeTag::seconds_ private
Seconds since Jan 1, 1900.
Definition at line 58 of file TimeTag.h.
Referenced by isImmediate(), operator<(), operator==(), operator>=(), seconds(), TimeTag(), TimeTag(), TimeTag(), TimeTag(), toNTP(), and toTimePoint().
The documentation for this class was generated from the following files:
include/osc/TimeTag.h
include/osc/Types.h
src/TimeTag.cpp