OSC++: osc::Value Class Reference
osc::Value Class Reference
Class representing an OSC value.
#include <Types.h>
Public Types
using Int32 = int32_t
using Int64 = int64_t
using Float = float
using Double = double
using String = std::string
using Symbol = std::string
using Bool = bool
using Char = char
using Nil = std::monostate
using Infinitum = std::monostate
using Variant
Public Member Functions
Value ()
Value (Variant value, bool isArrayElement=false)
Value (Int32 value, bool isArrayElement=false)
Value (Int64 value, bool isArrayElement=false)
Value (Float value, bool isArrayElement=false)
Value (Double value, bool isArrayElement=false)
Value (const char *value, bool isArrayElement=false)
Value (String value, bool isArrayElement=false)
Value (Symbol value, bool isArrayElement=false)
Value (Blob value, bool isArrayElement=false)
Value (TimeTag value, bool isArrayElement=false)
Value (Char value, bool isArrayElement=false)
Value (RGBAColor value, bool isArrayElement=false)
Value (MIDIMessage value, bool isArrayElement=false)
Value (Bool value, bool isArrayElement=false)
bool isInt32 () const
bool isInt64 () const
bool isFloat () const
bool isDouble () const
bool isString () const
bool isSymbol () const
bool isBlob () const
bool isTimeTag () const
bool isChar () const
bool isRGBA () const
bool isMIDI () const
bool isBool () const
bool isTrue () const
bool isFalse () const
bool isNil () const
bool isInfinitum () const
bool isArrayElement () const
Int32 asInt32 () const
Int64 asInt64 () const
Float asFloat () const
Double asDouble () const
String asString () const
Symbol asSymbol () const
Blob asBlob () const
TimeTag asTimeTag () const
Char asChar () const
RGBAColor asRGBA () const
MIDIMessage asMIDI () const
Bool asBool () const
char typeTag () const
const Variant & variant () const
void serialize (std::vector< std::byte > &buffer) const
Static Public Member Functions
static Value nil (bool isArrayElement=false)
static Value infinitum (bool isArrayElement=false)
static Value trueBool (bool isArrayElement=false)
static Value falseBool (bool isArrayElement=false)
static Value arrayBegin ()
static Value arrayEnd ()
static Value deserialize (const std::byte *&data, size_t &remainingSize, char typeTag)
Static Public Attributes
static constexpr char INT32_TAG = 'i'
static constexpr char INT64_TAG = 'h'
static constexpr char FLOAT_TAG = 'f'
static constexpr char DOUBLE_TAG = 'd'
static constexpr char STRING_TAG = 's'
static constexpr char SYMBOL_TAG = 'S'
static constexpr char BLOB_TAG = 'b'
static constexpr char TRUE_TAG = 'T'
static constexpr char FALSE_TAG = 'F'
static constexpr char NIL_TAG = 'N'
static constexpr char INFINITUM_TAG = 'I'
static constexpr char TIMETAG_TAG = 't'
static constexpr char CHAR_TAG = 'c'
static constexpr char RGBA_TAG = 'r'
static constexpr char MIDI_TAG = 'm'
static constexpr char ARRAY_BEGIN_TAG = '['
static constexpr char ARRAY_END_TAG = ']'
Private Attributes
Variant value_
bool isArrayElement_
Detailed Description
Class representing an OSC value.
OSC values can be of various types, represented here as a variant.
Definition at line 223 of file Types.h.
Member Typedef Documentation
Bool
using osc::Value::Bool = bool
Definition at line 251 of file Types.h.
Char
using osc::Value::Char = char
Definition at line 252 of file Types.h.
Double
using osc::Value::Double = double
Definition at line 248 of file Types.h.
Float
using osc::Value::Float = float
Definition at line 247 of file Types.h.
Infinitum
using osc::Value::Infinitum = std::monostate
Definition at line 254 of file Types.h.
Int32
using osc::Value::Int32 = int32_t
Definition at line 245 of file Types.h.
Int64
using osc::Value::Int64 = int64_t
Definition at line 246 of file Types.h.
Nil
using osc::Value::Nil = std::monostate
Definition at line 253 of file Types.h.
String
using osc::Value::String = std::string
Definition at line 249 of file Types.h.
Symbol
using osc::Value::Symbol = std::string
Definition at line 250 of file Types.h.
Variant
using osc::Value::Variant
Initial value:
 std::variant<Nil,
                                     Bool,
                                     Int32,
                                     Int64,
                                     Float,
                                     Double,
                                     String,
                                     Symbol,
                                     Blob,
                                     TimeTag,
                                     Char,
                                     RGBAColor,
                                     MIDIMessage,
                                     Infinitum
                                     >
Definition at line 257 of file Types.h.
Constructor & Destructor Documentation
Value() [1/15]
osc::Value::Value () inline
Definition at line 274 of file Types.h.
References isArrayElement_, and value_.
Referenced by arrayBegin(), arrayEnd(), deserialize(), falseBool(), infinitum(), nil(), trueBool(), and Value().
Value() [2/15]
osc::Value::Value (Variant value, bool isArrayElement = false) inline explicit
Definition at line 277 of file Types.h.
References isArrayElement(), isArrayElement_, and value_.
Value() [3/15]
osc::Value::Value (Int32 value, bool isArrayElement = false) explicit
Definition at line 73 of file Value.cpp.
References isArrayElement(), isArrayElement_, and value_.
Value() [4/15]
osc::Value::Value (Int64 value, bool isArrayElement = false) explicit
Definition at line 76 of file Value.cpp.
References isArrayElement(), isArrayElement_, and value_.
Value() [5/15]
osc::Value::Value (Float value, bool isArrayElement = false) explicit
Definition at line 79 of file Value.cpp.
References isArrayElement(), isArrayElement_, and value_.
Value() [6/15]
osc::Value::Value (Double value, bool isArrayElement = false) explicit
Definition at line 82 of file Value.cpp.
References isArrayElement(), isArrayElement_, and value_.
Value() [7/15]
osc::Value::Value (const char * value, bool isArrayElement = false) explicit
Definition at line 85 of file Value.cpp.
References isArrayElement(), isArrayElement_, and value_.
Value() [8/15]
osc::Value::Value (String value, bool isArrayElement = false) explicit
Definition at line 88 of file Value.cpp.
References isArrayElement(), isArrayElement_, and value_.
Value() [9/15]
osc::Value::Value (Symbol value, bool isArrayElement = false) explicit
References isArrayElement(), typeTag(), and Value().
Value() [10/15]
osc::Value::Value (Blob value, bool isArrayElement = false) explicit
Definition at line 94 of file Value.cpp.
References isArrayElement(), isArrayElement_, and value_.
Value() [11/15]
osc::Value::Value (TimeTag value, bool isArrayElement = false) explicit
Definition at line 97 of file Value.cpp.
References isArrayElement(), isArrayElement_, and value_.
Value() [12/15]
osc::Value::Value (Char value, bool isArrayElement = false) explicit
Definition at line 100 of file Value.cpp.
References isArrayElement(), isArrayElement_, and value_.
Value() [13/15]
osc::Value::Value (RGBAColor value, bool isArrayElement = false) explicit
Definition at line 103 of file Value.cpp.
References isArrayElement(), isArrayElement_, and value_.
Value() [14/15]
osc::Value::Value (MIDIMessage value, bool isArrayElement = false) explicit
Definition at line 106 of file Value.cpp.
References isArrayElement(), isArrayElement_, and value_.
Value() [15/15]
osc::Value::Value (Bool value, bool isArrayElement = false) explicit
Definition at line 109 of file Value.cpp.
References isArrayElement(), isArrayElement_, and value_.
Member Function Documentation
arrayBegin()
Value osc::Value::arrayBegin () static
Definition at line 131 of file Value.cpp.
References isArrayElement_, and Value().
Referenced by osc::Message::addArray(), and osc::Message::deserialize().
arrayEnd()
Value osc::Value::arrayEnd () static
Definition at line 137 of file Value.cpp.
References isArrayElement_, and Value().
Referenced by osc::Message::addArray(), and osc::Message::deserialize().
asBlob()
Blob osc::Value::asBlob () const
Definition at line 197 of file Value.cpp.
References isBlob(), and value_.
Referenced by serialize().
asBool()
Value::Bool osc::Value::asBool () const
Definition at line 222 of file Value.cpp.
References isBool(), and value_.
asChar()
Value::Char osc::Value::asChar () const
Definition at line 207 of file Value.cpp.
References isChar(), and value_.
Referenced by serialize().
asDouble()
Value::Double osc::Value::asDouble () const
Definition at line 182 of file Value.cpp.
References isDouble(), and value_.
Referenced by serialize().
asFloat()
Value::Float osc::Value::asFloat () const
Definition at line 177 of file Value.cpp.
References isFloat(), and value_.
Referenced by serialize().
asInt32()
Value::Int32 osc::Value::asInt32 () const
Definition at line 167 of file Value.cpp.
References isInt32(), and value_.
Referenced by serialize().
asInt64()
Value::Int64 osc::Value::asInt64 () const
Definition at line 172 of file Value.cpp.
References isInt64(), and value_.
Referenced by serialize().
asMIDI()
MIDIMessage osc::Value::asMIDI () const
Definition at line 217 of file Value.cpp.
References isMIDI(), and value_.
Referenced by serialize().
asRGBA()
RGBAColor osc::Value::asRGBA () const
Definition at line 212 of file Value.cpp.
References isRGBA(), and value_.
Referenced by serialize().
asString()
Value::String osc::Value::asString () const
Definition at line 187 of file Value.cpp.
References isString(), and value_.
Referenced by serialize().
asSymbol()
Value::Symbol osc::Value::asSymbol () const
Definition at line 192 of file Value.cpp.
References isSymbol(), and value_.
Referenced by serialize().
asTimeTag()
TimeTag osc::Value::asTimeTag () const
Definition at line 202 of file Value.cpp.
References isTimeTag(), and value_.
Referenced by serialize().
deserialize()
Value osc::Value::deserialize (const std::byte *& data, size_t & remainingSize, char typeTag) static
Definition at line 364 of file Value.cpp.
References osc::bigEndian(), BLOB_TAG, CHAR_TAG, DOUBLE_TAG, FALSE_TAG, falseBool(), FLOAT_TAG, infinitum(), INFINITUM_TAG, INT32_TAG, INT64_TAG, osc::MAX_BLOB_SIZE, MIDI_TAG, nil(), NIL_TAG, osc::padSize(), RGBA_TAG, STRING_TAG, SYMBOL_TAG, TIMETAG_TAG, TRUE_TAG, trueBool(), typeTag(), and Value().
Referenced by osc::Message::deserialize().
falseBool()
Value osc::Value::falseBool (bool isArrayElement = false) static
Definition at line 129 of file Value.cpp.
References isArrayElement(), and Value().
Referenced by osc::Message::addFalse(), and deserialize().
infinitum()
Value osc::Value::infinitum (bool isArrayElement = false) static
Definition at line 120 of file Value.cpp.
References isArrayElement(), isArrayElement_, Value(), and value_.
Referenced by osc::Message::addInfinitum(), and deserialize().
isArrayElement()
bool osc::Value::isArrayElement () const
Definition at line 164 of file Value.cpp.
References isArrayElement_.
Referenced by falseBool(), infinitum(), nil(), trueBool(), Value(), Value(), Value(), Value(), Value(), Value(), Value(), Value(), Value(), Value(), Value(), Value(), Value(), and Value().
isBlob()
bool osc::Value::isBlob () const
Definition at line 150 of file Value.cpp.
References value_.
Referenced by asBlob(), and typeTag().
isBool()
bool osc::Value::isBool () const
Definition at line 155 of file Value.cpp.
References value_.
Referenced by asBool(), isFalse(), and isTrue().
isChar()
bool osc::Value::isChar () const
Definition at line 152 of file Value.cpp.
References value_.
Referenced by asChar(), and typeTag().
isDouble()
bool osc::Value::isDouble () const
Definition at line 147 of file Value.cpp.
References value_.
Referenced by asDouble(), and typeTag().
isFalse()
bool osc::Value::isFalse () const
Definition at line 157 of file Value.cpp.
References isBool(), and value_.
Referenced by typeTag().
isFloat()
bool osc::Value::isFloat () const
Definition at line 146 of file Value.cpp.
References value_.
Referenced by asFloat(), and typeTag().
isInfinitum()
bool osc::Value::isInfinitum () const
Definition at line 161 of file Value.cpp.
References value_.
Referenced by typeTag().
isInt32()
bool osc::Value::isInt32 () const
Definition at line 144 of file Value.cpp.
References value_.
Referenced by asInt32(), and typeTag().
isInt64()
bool osc::Value::isInt64 () const
Definition at line 145 of file Value.cpp.
References value_.
Referenced by asInt64(), and typeTag().
isMIDI()
bool osc::Value::isMIDI () const
Definition at line 154 of file Value.cpp.
References value_.
Referenced by asMIDI(), and typeTag().
isNil()
bool osc::Value::isNil () const
Definition at line 158 of file Value.cpp.
References value_.
Referenced by typeTag().
isRGBA()
bool osc::Value::isRGBA () const
Definition at line 153 of file Value.cpp.
References value_.
Referenced by asRGBA(), and typeTag().
isString()
bool osc::Value::isString () const
Definition at line 148 of file Value.cpp.
References value_.
Referenced by asString(), and typeTag().
isSymbol()
bool osc::Value::isSymbol () const
Definition at line 149 of file Value.cpp.
References value_.
Referenced by asSymbol(), and typeTag().
isTimeTag()
bool osc::Value::isTimeTag () const
Definition at line 151 of file Value.cpp.
References value_.
Referenced by asTimeTag(), and typeTag().
isTrue()
bool osc::Value::isTrue () const
Definition at line 156 of file Value.cpp.
References isBool(), and value_.
Referenced by typeTag().
nil()
Value osc::Value::nil (bool isArrayElement = false) static
Definition at line 113 of file Value.cpp.
References isArrayElement(), isArrayElement_, Value(), and value_.
Referenced by osc::Message::addNil(), and deserialize().
serialize()
void osc::Value::serialize (std::vector< std::byte > & buffer) const
Definition at line 251 of file Value.cpp.
References osc::RGBAColor::a, asBlob(), asChar(), asDouble(), asFloat(), asInt32(), asInt64(), asMIDI(), asRGBA(), asString(), asSymbol(), asTimeTag(), osc::RGBAColor::b, osc::bigEndian(), BLOB_TAG, osc::Blob::bytes(), osc::MIDIMessage::bytes, CHAR_TAG, DOUBLE_TAG, FALSE_TAG, FLOAT_TAG, osc::RGBAColor::g, INFINITUM_TAG, INT32_TAG, INT64_TAG, MIDI_TAG, NIL_TAG, osc::padSize(), osc::RGBAColor::r, RGBA_TAG, osc::Blob::size(), STRING_TAG, SYMBOL_TAG, TIMETAG_TAG, osc::TimeTag::toNTP(), TRUE_TAG, and typeTag().
trueBool()
Value osc::Value::trueBool (bool isArrayElement = false) static
Definition at line 127 of file Value.cpp.
References isArrayElement(), and Value().
Referenced by osc::Message::addTrue(), and deserialize().
typeTag()
char osc::Value::typeTag () const
Definition at line 227 of file Value.cpp.
References BLOB_TAG, CHAR_TAG, DOUBLE_TAG, FALSE_TAG, FLOAT_TAG, INFINITUM_TAG, INT32_TAG, INT64_TAG, isBlob(), isChar(), isDouble(), isFalse(), isFloat(), isInfinitum(), isInt32(), isInt64(), isMIDI(), isNil(), isRGBA(), isString(), isSymbol(), isTimeTag(), isTrue(), MIDI_TAG, NIL_TAG, RGBA_TAG, STRING_TAG, SYMBOL_TAG, TIMETAG_TAG, and TRUE_TAG.
Referenced by deserialize(), serialize(), and Value().
variant()
const Value::Variant & osc::Value::variant () const
Definition at line 248 of file Value.cpp.
References value_.
Member Data Documentation
ARRAY_BEGIN_TAG
char osc::Value::ARRAY_BEGIN_TAG = '[' static constexpr
Definition at line 241 of file Types.h.
Referenced by osc::Message::deserialize().
ARRAY_END_TAG
char osc::Value::ARRAY_END_TAG = ']' static constexpr
Definition at line 242 of file Types.h.
Referenced by osc::Message::deserialize().
BLOB_TAG
char osc::Value::BLOB_TAG = 'b' static constexpr
Definition at line 232 of file Types.h.
Referenced by deserialize(), serialize(), and typeTag().
CHAR_TAG
char osc::Value::CHAR_TAG = 'c' static constexpr
Definition at line 238 of file Types.h.
Referenced by deserialize(), serialize(), and typeTag().
DOUBLE_TAG
char osc::Value::DOUBLE_TAG = 'd' static constexpr
Definition at line 229 of file Types.h.
Referenced by deserialize(), serialize(), and typeTag().
FALSE_TAG
char osc::Value::FALSE_TAG = 'F' static constexpr
Definition at line 234 of file Types.h.
Referenced by deserialize(), serialize(), and typeTag().
FLOAT_TAG
char osc::Value::FLOAT_TAG = 'f' static constexpr
Definition at line 228 of file Types.h.
Referenced by deserialize(), serialize(), and typeTag().
INFINITUM_TAG
char osc::Value::INFINITUM_TAG = 'I' static constexpr
Definition at line 236 of file Types.h.
Referenced by deserialize(), serialize(), and typeTag().
INT32_TAG
char osc::Value::INT32_TAG = 'i' static constexpr
Definition at line 226 of file Types.h.
Referenced by deserialize(), serialize(), and typeTag().
INT64_TAG
char osc::Value::INT64_TAG = 'h' static constexpr
Definition at line 227 of file Types.h.
Referenced by deserialize(), serialize(), and typeTag().
isArrayElement_
bool osc::Value::isArrayElement_ private
Definition at line 348 of file Types.h.
Referenced by arrayBegin(), arrayEnd(), infinitum(), isArrayElement(), nil(), Value(), Value(), Value(), Value(), Value(), Value(), Value(), Value(), Value(), Value(), Value(), Value(), Value(), and Value().
MIDI_TAG
char osc::Value::MIDI_TAG = 'm' static constexpr
Definition at line 240 of file Types.h.
Referenced by deserialize(), serialize(), and typeTag().
NIL_TAG
char osc::Value::NIL_TAG = 'N' static constexpr
Definition at line 235 of file Types.h.
Referenced by deserialize(), serialize(), and typeTag().
RGBA_TAG
char osc::Value::RGBA_TAG = 'r' static constexpr
Definition at line 239 of file Types.h.
Referenced by deserialize(), serialize(), and typeTag().
STRING_TAG
char osc::Value::STRING_TAG = 's' static constexpr
Definition at line 230 of file Types.h.
Referenced by deserialize(), serialize(), and typeTag().
SYMBOL_TAG
char osc::Value::SYMBOL_TAG = 'S' static constexpr
Definition at line 231 of file Types.h.
Referenced by deserialize(), serialize(), and typeTag().
TIMETAG_TAG
char osc::Value::TIMETAG_TAG = 't' static constexpr
Definition at line 237 of file Types.h.
Referenced by deserialize(), serialize(), and typeTag().
TRUE_TAG
char osc::Value::TRUE_TAG = 'T' static constexpr
Definition at line 233 of file Types.h.
Referenced by deserialize(), serialize(), and typeTag().
value_
Variant osc::Value::value_ private
Definition at line 347 of file Types.h.
Referenced by asBlob(), asBool(), asChar(), asDouble(), asFloat(), asInt32(), asInt64(), asMIDI(), asRGBA(), asString(), asSymbol(), asTimeTag(), infinitum(), isBlob(), isBool(), isChar(), isDouble(), isFalse(), isFloat(), isInfinitum(), isInt32(), isInt64(), isMIDI(), isNil(), isRGBA(), isString(), isSymbol(), isTimeTag(), isTrue(), nil(), Value(), Value(), Value(), Value(), Value(), Value(), Value(), Value(), Value(), Value(), Value(), Value(), Value(), Value(), and variant().
The documentation for this class was generated from the following files:
include/osc/Types.h
src/Value.cpp