OSC++: osc::Message Class Reference
osc::Message Class Reference
The Message class represents an OSC message.
#include <Message.h>
Public Member Functions
Message (const std::string &path)
Construct a new OSC Message object.
std::string getPath () const
Get the OSC address path.
const std::vector< Value > & getArguments () const
Get the arguments in this message.
Message & addInt32 (int32_t value)
Add an Int32 argument (type tag 'i')
Message & addInt64 (int64_t value)
Add an Int64 argument (type tag 'h')
Message & addFloat (float value)
Add a Float argument (type tag 'f')
Message & addDouble (double value)
Add a Double argument (type tag 'd')
Message & addString (const std::string &value)
Add a String argument (type tag 's')
Message & addSymbol (const std::string &value)
Add a Symbol argument (type tag 'S')
Message & addBlob (const void *data, size_t size)
Add a Blob argument (type tag 'b')
Message & addTimeTag (const TimeTag &timeTag)
Add a TimeTag argument (type tag 't')
Message & addChar (char value)
Add a Character argument (type tag 'c')
Message & addColor (uint32_t value)
Add a RGBA Color argument (type tag 'r')
Message & addMidi (uint8_t port, uint8_t status, uint8_t data1, uint8_t data2)
Add a MIDI message argument (type tag 'm')
Message & addTrue ()
Add a True argument (type tag 'T')
Message & addFalse ()
Add a False argument (type tag 'F')
Message & addBool (bool value)
Add a boolean argument (type tag 'T' or 'F')
Message & addNil ()
Add a Nil argument (type tag 'N')
Message & addInfinitum ()
Add an Infinitum argument (type tag 'I')
Message & addArray (const std::vector< Value > &array)
Add an Array of arguments (type tags '[ ... ]')
Message & addValue (const Value &value)
Add a generic Value argument.
std::vector< std::byte > serialize () const
Serialize the message to the OSC binary format.
Static Public Member Functions
static Message deserialize (const std::byte *data, size_t size)
Deserialize a message from OSC binary format.
Private Attributes
std::string path_
std::vector< Value > arguments_
Detailed Description
The Message class represents an OSC message.
Definition at line 20 of file Message.h.
Constructor & Destructor Documentation
Message()
osc::Message::Message (const std::string & path) explicit
Construct a new OSC Message object.
Parameters
path The OSC address path (must start with '/')
Definition at line 10 of file Message.cpp.
References path_.
Referenced by addArray(), addBlob(), addBool(), addChar(), addColor(), addDouble(), addFalse(), addFloat(), addInfinitum(), addInt32(), addInt64(), addMidi(), addNil(), addString(), addSymbol(), addTimeTag(), addTrue(), addValue(), and deserialize().
Member Function Documentation
addArray()
Message & osc::Message::addArray (const std::vector< Value > & array)
Add an Array of arguments (type tags '[ ... ]')
Parameters
array The array of values to add
Returns
Reference to this message for method chaining
Definition at line 131 of file Message.cpp.
References arguments_, osc::Value::arrayBegin(), osc::Value::arrayEnd(), and Message().
addBlob()
Message & osc::Message::addBlob (const void * data, size_t size)
Add a Blob argument (type tag 'b')
Parameters
data Pointer to the binary data
size Size of the binary data in bytes
Returns
Reference to this message for method chaining
Definition at line 62 of file Message.cpp.
References arguments_, and Message().
addBool()
Message & osc::Message::addBool (bool value)
Add a boolean argument (type tag 'T' or 'F')
Parameters
value The boolean value to add
Returns
Reference to this message for method chaining
Definition at line 111 of file Message.cpp.
References addFalse(), addTrue(), and Message().
addChar()
Message & osc::Message::addChar (char value)
Add a Character argument (type tag 'c')
Parameters
value The character value to add
Returns
Reference to this message for method chaining
Definition at line 74 of file Message.cpp.
References arguments_, and Message().
addColor()
Message & osc::Message::addColor (uint32_t value)
Add a RGBA Color argument (type tag 'r')
Parameters
value The RGBA color value to add (packed as a uint32_t)
Returns
Reference to this message for method chaining
Definition at line 80 of file Message.cpp.
References osc::RGBAColor::a, arguments_, osc::RGBAColor::b, osc::RGBAColor::g, Message(), and osc::RGBAColor::r.
addDouble()
Message & osc::Message::addDouble (double value)
Add a Double argument (type tag 'd')
Parameters
value The double value to add
Returns
Reference to this message for method chaining
Definition at line 43 of file Message.cpp.
References arguments_, and Message().
addFalse()
Message & osc::Message::addFalse ()
Add a False argument (type tag 'F')
Returns
Reference to this message for method chaining
Definition at line 105 of file Message.cpp.
References arguments_, osc::Value::falseBool(), and Message().
Referenced by addBool().
addFloat()
Message & osc::Message::addFloat (float value)
Add a Float argument (type tag 'f')
Parameters
value The float value to add
Returns
Reference to this message for method chaining
Definition at line 37 of file Message.cpp.
References arguments_, and Message().
addInfinitum()
Message & osc::Message::addInfinitum ()
Add an Infinitum argument (type tag 'I')
Returns
Reference to this message for method chaining
Definition at line 125 of file Message.cpp.
References arguments_, osc::Value::infinitum(), and Message().
addInt32()
Message & osc::Message::addInt32 (int32_t value)
Add an Int32 argument (type tag 'i')
Parameters
value The integer value to add
Returns
Reference to this message for method chaining
Definition at line 25 of file Message.cpp.
References arguments_, and Message().
addInt64()
Message & osc::Message::addInt64 (int64_t value)
Add an Int64 argument (type tag 'h')
Parameters
value The int64 value to add
Returns
Reference to this message for method chaining
Definition at line 31 of file Message.cpp.
References arguments_, and Message().
addMidi()
Message & osc::Message::addMidi (uint8_t port, uint8_t status, uint8_t data1, uint8_t data2)
Add a MIDI message argument (type tag 'm')
Parameters
port Port ID (byte 0)
status Status byte (byte 1)
data1 Data byte 1 (byte 2)
data2 Data byte 2 (byte 3)
Returns
Reference to this message for method chaining
Definition at line 91 of file Message.cpp.
References arguments_, osc::MIDIMessage::bytes, and Message().
addNil()
Message & osc::Message::addNil ()
Add a Nil argument (type tag 'N')
Returns
Reference to this message for method chaining
Definition at line 119 of file Message.cpp.
References arguments_, Message(), and osc::Value::nil().
addString()
Message & osc::Message::addString (const std::string & value)
Add a String argument (type tag 's')
Parameters
value The string value to add
Returns
Reference to this message for method chaining
Definition at line 49 of file Message.cpp.
References arguments_, and Message().
addSymbol()
Message & osc::Message::addSymbol (const std::string & value)
Add a Symbol argument (type tag 'S')
Parameters
value The symbol string to add
Returns
Reference to this message for method chaining
Definition at line 55 of file Message.cpp.
References arguments_, and Message().
addTimeTag()
Message & osc::Message::addTimeTag (const TimeTag & timeTag)
Add a TimeTag argument (type tag 't')
Parameters
timeTag The time tag value to add
Returns
Reference to this message for method chaining
Definition at line 68 of file Message.cpp.
References arguments_, and Message().
addTrue()
Message & osc::Message::addTrue ()
Add a True argument (type tag 'T')
Returns
Reference to this message for method chaining
Definition at line 99 of file Message.cpp.
References arguments_, Message(), and osc::Value::trueBool().
Referenced by addBool().
addValue()
Message & osc::Message::addValue (const Value & value)
Add a generic Value argument.
Parameters
value The OSC value to add
Returns
Reference to this message for method chaining
Definition at line 157 of file Message.cpp.
References arguments_, and Message().
deserialize()
Message osc::Message::deserialize (const std::byte * data, size_t size) static
Deserialize a message from OSC binary format.
Parameters
data Pointer to the binary data
size Size of the binary data in bytes
Returns
The deserialized Message object
Exceptions
OSCException if the data is invalid
Definition at line 278 of file Message.cpp.
References osc::OSCException::AddressError, arguments_, osc::Value::ARRAY_BEGIN_TAG, osc::Value::ARRAY_END_TAG, osc::Value::arrayBegin(), osc::Value::arrayEnd(), osc::Value::deserialize(), osc::OSCException::MalformedPacket, Message(), and osc::padSize().
Referenced by osc::Bundle::deserialize(), and osc::ServerImpl::receive().
getArguments()
const std::vector< Value > & osc::Message::getArguments () const
Get the arguments in this message.
Returns
A const reference to the argument vector
Definition at line 22 of file Message.cpp.
References arguments_.
Referenced by osc::ServerImpl::dispatchMessage().
getPath()
std::string osc::Message::getPath () const
Get the OSC address path.
Returns
The path as a string
Definition at line 19 of file Message.cpp.
References path_.
Referenced by osc::ServerImpl::dispatchMessage().
serialize()
std::vector< std::byte > osc::Message::serialize () const
Serialize the message to the OSC binary format.
Returns
Vector of bytes representing the serialized message
Definition at line 166 of file Message.cpp.
References arguments_, osc::padSize(), and path_.
Referenced by osc::Address::send().
Member Data Documentation
arguments_
std::vector<Value> osc::Message::arguments_ private
Definition at line 184 of file Message.h.
Referenced by addArray(), addBlob(), addChar(), addColor(), addDouble(), addFalse(), addFloat(), addInfinitum(), addInt32(), addInt64(), addMidi(), addNil(), addString(), addSymbol(), addTimeTag(), addTrue(), addValue(), deserialize(), getArguments(), and serialize().
path_
std::string osc::Message::path_ private
Definition at line 183 of file Message.h.
Referenced by getPath(), Message(), and serialize().
The documentation for this class was generated from the following files:
include/osc/Message.h
src/Message.cpp