OSC++: osc::Bundle Class Reference
osc::Bundle Class Reference
The Bundle class represents an OSC bundle, which is a collection of OSC messages or other bundles that should be executed atomically and potentially at a specific time.
#include <Bundle.h>
Public Member Functions
Bundle (const TimeTag &timeTag=TimeTag::immediate())
Construct a new Bundle object with the specified time tag.
Bundle & addMessage (const Message &message)
Add a message to this bundle.
Bundle & addBundle (const Bundle &bundle)
Add another bundle as a child of this bundle.
TimeTag getTimeTag () const
Get the time tag for this bundle.
const std::vector< Message > & messages () const
Get the messages in this bundle.
const std::vector< Bundle > & bundles () const
Get the child bundles in this bundle.
std::vector< std::byte > serialize () const
Serialize the bundle to the OSC binary format.
void forEach (std::function< void(const Message &)> callback) const
Execute a function for each message in the bundle and its sub-bundles.
Static Public Member Functions
static Bundle deserialize (const std::byte *data, size_t size)
Deserialize a bundle from OSC binary format.
Private Attributes
TimeTag timeTag_
std::vector< Message > messages_
std::vector< Bundle > childBundles_
Detailed Description
The Bundle class represents an OSC bundle, which is a collection of OSC messages or other bundles that should be executed atomically and potentially at a specific time.
Definition at line 16 of file Bundle.h.
Constructor & Destructor Documentation
Bundle()
osc::Bundle::Bundle (const TimeTag & timeTag = TimeTag::immediate()) explicit
Construct a new Bundle object with the specified time tag.
Parameters
timeTag The time at which this bundle should be executed (default: immediate)
Definition at line 14 of file Bundle.cpp.
References timeTag_.
Referenced by addBundle(), addMessage(), and deserialize().
Member Function Documentation
addBundle()
Bundle & osc::Bundle::addBundle (const Bundle & bundle)
Add another bundle as a child of this bundle.
Parameters
bundle The child bundle to add
Returns
Reference to this bundle for method chaining
Definition at line 23 of file Bundle.cpp.
References Bundle(), and childBundles_.
Referenced by deserialize().
addMessage()
Bundle & osc::Bundle::addMessage (const Message & message)
Add a message to this bundle.
Parameters
message The OSC message to add
Returns
Reference to this bundle for method chaining
Definition at line 17 of file Bundle.cpp.
References Bundle(), and messages_.
Referenced by deserialize().
bundles()
const std::vector< Bundle > & osc::Bundle::bundles () const
Get the child bundles in this bundle.
Returns
Const reference to the vector of child bundles
Definition at line 35 of file Bundle.cpp.
References childBundles_.
deserialize()
Bundle osc::Bundle::deserialize (const std::byte * data, size_t size) static
Deserialize a bundle from OSC binary format.
Parameters
data Pointer to the binary data
size Size of the binary data in bytes
Returns
The deserialized Bundle object
Exceptions
OSCException if the data is invalid
Definition at line 151 of file Bundle.cpp.
References addBundle(), addMessage(), Bundle(), osc::OSCException::code(), osc::OSCException::DeserializationError, deserialize(), osc::Message::deserialize(), osc::OSCException::InvalidArgument, and osc::OSCException::MalformedPacket.
Referenced by deserialize(), and osc::ServerImpl::receive().
forEach()
void osc::Bundle::forEach (std::function< void(const Message &)> callback) const
Execute a function for each message in the bundle and its sub-bundles.
Parameters
callback The function to call for each message
Definition at line 271 of file Bundle.cpp.
References childBundles_, and messages_.
getTimeTag()
TimeTag osc::Bundle::getTimeTag () const
Get the time tag for this bundle.
Returns
The time tag
Definition at line 29 of file Bundle.cpp.
References timeTag_.
messages()
const std::vector< Message > & osc::Bundle::messages () const
Get the messages in this bundle.
Returns
Const reference to the vector of messages
Definition at line 32 of file Bundle.cpp.
References messages_.
Referenced by osc::ServerImpl::dispatchBundle().
serialize()
std::vector< std::byte > osc::Bundle::serialize () const
Serialize the bundle to the OSC binary format.
Returns
Vector of bytes representing the serialized bundle
Definition at line 41 of file Bundle.cpp.
References childBundles_, osc::OSCException::code(), messages_, osc::padSize(), osc::OSCException::SerializationError, and timeTag_.
Referenced by osc::Address::send().
Member Data Documentation
childBundles_
std::vector<Bundle> osc::Bundle::childBundles_ private
Definition at line 81 of file Bundle.h.
Referenced by addBundle(), bundles(), forEach(), and serialize().
messages_
std::vector<Message> osc::Bundle::messages_ private
Definition at line 80 of file Bundle.h.
Referenced by addMessage(), forEach(), messages(), and serialize().
timeTag_
TimeTag osc::Bundle::timeTag_ private
Definition at line 79 of file Bundle.h.
Referenced by Bundle(), getTimeTag(), and serialize().
The documentation for this class was generated from the following files:
include/osc/Bundle.h
src/Bundle.cpp