OSC++: osc::AddressException Class Reference
osc::AddressException Class Reference
Exception for address errors.
#include <Exceptions.h>
Public Member Functions
AddressException (const std::string &message)
AddressException (const std::string &message, ErrorCode code)
Public Member Functions inherited from osc::OSCException
OSCException (const std::string &message, ErrorCode code=ErrorCode::None)
Construct a new OSC Exception.
ErrorCode code () const
Get the error code.
Additional Inherited Members
Public Types inherited from osc::OSCException
enum class ErrorCode {
None = 0 , NetworkError , MalformedPacket , TypeMismatch ,
BufferOverflow , UnknownType , AddressError , InvalidArgument ,
InvalidMessage , InvalidBundle , PatternError , ServerError ,
ClientError , OutOfMemory , NotImplemented , SocketError ,
NetworkingError , MessageTooLarge , DeserializationError , SerializationError ,
MatchError
}
Error codes for OSC exceptions.
Static Public Member Functions inherited from osc::OSCException
static std::string getErrorDescription (ErrorCode code)
Get a description for an error code.
Detailed Description
Exception for address errors.
Definition at line 120 of file Exceptions.h.
Constructor & Destructor Documentation
AddressException() [1/2]
osc::AddressException::AddressException (const std::string & message) inline
Definition at line 122 of file Exceptions.h.
References osc::OSCException::AddressError, and osc::OSCException::OSCException().
AddressException() [2/2]
osc::AddressException::AddressException (const std::string & message, ErrorCode code) inline
Definition at line 125 of file Exceptions.h.
References osc::OSCException::code(), and osc::OSCException::OSCException().
The documentation for this class was generated from the following file:
include/osc/Exceptions.h