OSC++: osc Namespace Reference
osc Namespace Reference
Namespace containing all OSC library components.
Namespaces
namespace tcp_framing
Classes
class Address
class AddressException
Exception for address errors.
class AddressImpl
class Blob
Class representing an OSC Blob.
class BufferOverflowException
Exception for buffer overflows.
class Bundle
The Bundle class represents an OSC bundle, which is a collection of OSC messages or other bundles that should be executed atomically and potentially at a specific time.
class ClientException
Exception for client errors.
class DeserializationException
Exception for deserialization errors.
class InvalidArgumentException
Exception for invalid arguments.
class InvalidBundleException
Exception for invalid bundles.
class InvalidMessageException
Exception for invalid messages.
class MalformedPacketException
Exception for malformed packets.
class MatchException
Exception for pattern matching errors.
class Message
The Message class represents an OSC message.
class MessageSizeException
Exception for message size errors.
struct Method
struct MIDIMessage
Structure for MIDI message (OSC type 'm')
class NetworkException
Exception for network-related errors.
class NetworkingException
Exception for networking subsystem errors.
class NotImplementedException
Exception for not implemented features.
class OSCException
Base exception class for all OSC-related errors.
class OutOfMemoryException
Exception for out of memory errors.
class PatternException
Exception for pattern errors.
class PlatformException
Exception for platform-specific errors.
struct RGBAColor
Structure for RGBA color (OSC type 'r')
class SerializationException
Exception for serialization errors.
class Server
The Server class handles incoming OSC messages.
class ServerException
Exception for server errors.
class ServerImpl
class ServerThread
Class for running an OSC server in a separate thread.
class SocketException
Exception for socket errors.
class TimeTag
Class representing an OSC Time Tag.
class TypeMismatchException
Exception for type mismatches.
class UnknownTypeException
Exception for unknown types.
class Value
Class representing an OSC value.
Typedefs
using MethodId = int
using MethodHandler = std::function<void(const Message &)>
using BundleStartHandler = std::function<void(const Bundle &)>
using BundleEndHandler = std::function<void(const Bundle &)>
using ErrorHandler = std::function<void(int, const std::string &, const std::string &)>
using SOCKET_TYPE = int
Enumerations
enum class Protocol { UDP , TCP , UNIX }
Enumeration of supported transport protocols.
Functions
std::string getVersionString ()
Get the library version as a string.
void getVersion (int &major, int &minor, int &patch)
Get the library version as components.
size_t padSize (size_t size)
bool initialize ()
Initialize the OSC library.
void cleanup ()
Clean up the OSC library.
Message createMessage (const std::string &path)
Create a new OSC message.
Bundle createBundle (const TimeTag &timeTag=TimeTag::immediate())
Create a new OSC bundle.
Server createServer (const std::string &port, Protocol protocol=Protocol::UDP)
Create an OSC server.
Address createAddress (const std::string &host, const std::string &port, Protocol protocol=Protocol::UDP)
Create an OSC address for sending messages.
void getLibraryVersion (int &major, int &minor, int &patch)
Get the version of the OSC library.
std::string getLibraryVersionString ()
Get the version string of the OSC library.
bool isInitialized ()
Check if the OSC library is initialized.
uint32_t bigEndian (uint32_t x)
int32_t bigEndian (int32_t x)
uint64_t bigEndian (uint64_t x)
int64_t bigEndian (int64_t x)
float bigEndian (float x)
double bigEndian (double x)
Variables
constexpr size_t MAX_MESSAGE_SIZE = 16777216
constexpr size_t MAX_BLOB_SIZE = 33554432
Detailed Description
Namespace containing all OSC library components.
Typedef Documentation
BundleEndHandler
using osc::BundleEndHandler = std::function<void(const Bundle &)>
Definition at line 24 of file ServerImpl.h.
BundleStartHandler
using osc::BundleStartHandler = std::function<void(const Bundle &)>
Definition at line 23 of file ServerImpl.h.
ErrorHandler
using osc::ErrorHandler = std::function<void(int, const std::string &, const std::string &)>
Definition at line 25 of file ServerImpl.h.
MethodHandler
using osc::MethodHandler = std::function<void(const Message &)>
Definition at line 22 of file ServerImpl.h.
MethodId
using osc::MethodId = int
Definition at line 21 of file ServerImpl.h.
SOCKET_TYPE
using osc::SOCKET_TYPE = int
Definition at line 43 of file Types.h.
Enumeration Type Documentation
Protocol
enum class osc::Protocol strong
Enumeration of supported transport protocols.
Enumerator
UDP
User Datagram Protocol.
TCP
Transmission Control Protocol.
UNIX
Unix Domain Socket.
Definition at line 56 of file Types.h.
Function Documentation
bigEndian() [1/6]
double osc::bigEndian (double x) inline
Definition at line 64 of file Value.cpp.
References bigEndian().
bigEndian() [2/6]
float osc::bigEndian (float x) inline
Definition at line 56 of file Value.cpp.
References bigEndian().
bigEndian() [3/6]
int32_t osc::bigEndian (int32_t x) inline
Definition at line 37 of file Value.cpp.
bigEndian() [4/6]
int64_t osc::bigEndian (int64_t x) inline
Definition at line 52 of file Value.cpp.
References bigEndian().
bigEndian() [5/6]
uint32_t osc::bigEndian (uint32_t x) inline
Definition at line 35 of file Value.cpp.
Referenced by bigEndian(), bigEndian(), bigEndian(), osc::Value::deserialize(), and osc::Value::serialize().
bigEndian() [6/6]
uint64_t osc::bigEndian (uint64_t x) inline
Definition at line 41 of file Value.cpp.
cleanup()
void osc::cleanup ()
Clean up the OSC library.
This function cleans up any resources allocated by the OSC library. Call this when you're done using OSC, typically at application shutdown.
Definition at line 61 of file main.cpp.
References osc::AddressImpl::cleanupNetworking().
createAddress()
Address osc::createAddress (const std::string & host, const std::string & port, Protocol protocol = Protocol::UDP)
Create an OSC address for sending messages.
Convenience function to create a new OSC address for the specified host and port.
Parameters
host Hostname or IP address
port Port number or service name
protocol Transport protocol (UDP, TCP, or UNIX)
Returns
A new OSC address
Definition at line 113 of file main.cpp.
References UDP.
createBundle()
Bundle osc::createBundle (const TimeTag & timeTag = TimeTag::immediate())
Create a new OSC bundle.
Convenience function to create a new OSC bundle with the given time tag.
Parameters
timeTag OSC time tag for the bundle
Returns
A new OSC bundle
Definition at line 88 of file main.cpp.
References osc::TimeTag::immediate().
createMessage()
Message osc::createMessage (const std::string & path)
Create a new OSC message.
Convenience function to create a new OSC message with the given address pattern.
Parameters
path OSC address pattern
Returns
A new OSC message
Definition at line 78 of file main.cpp.
createServer()
Server osc::createServer (const std::string & port, Protocol protocol = Protocol::UDP)
Create an OSC server.
Convenience function to create a new OSC server listening on the specified port.
Parameters
port Port number or service name to listen on
protocol Transport protocol (UDP, TCP, or UNIX)
Returns
A new OSC server
Definition at line 99 of file main.cpp.
References UDP.
getLibraryVersion()
void osc::getLibraryVersion (int & major, int & minor, int & patch)
Get the version of the OSC library.
Parameters
major Reference to receive the major version number
minor Reference to receive the minor version number
patch Reference to receive the patch version number
Definition at line 125 of file main.cpp.
References getVersion().
getLibraryVersionString()
std::string osc::getLibraryVersionString ()
Get the version string of the OSC library.
Returns
Version string in format "major.minor.patch"
Definition at line 132 of file main.cpp.
References getVersionString().
getVersion()
void osc::getVersion (int & major, int & minor, int & patch) inline
Get the library version as components.
Parameters
major Receives the major version number
minor Receives the minor version number
patch Receives the patch version number
Definition at line 78 of file OSC.h.
References OSC_VERSION_MAJOR, OSC_VERSION_MINOR, and OSC_VERSION_PATCH.
Referenced by getLibraryVersion().
getVersionString()
std::string osc::getVersionString () inline
Get the library version as a string.
Returns
Version string in format "major.minor.patch"
Definition at line 70 of file OSC.h.
References OSC_VERSION_STRING.
Referenced by getLibraryVersionString().
initialize()
bool osc::initialize ()
Initialize the OSC library.
This function initializes any required platform-specific resources (like Windows sockets) needed by the OSC library. Call this before any other OSC function.
Returns
true if initialization succeeded, false otherwise
Definition at line 34 of file main.cpp.
References osc::OSCException::code(), and osc::AddressImpl::initializeNetworking().
isInitialized()
bool osc::isInitialized ()
Check if the OSC library is initialized.
Returns
true if the library is initialized, false otherwise
Definition at line 161 of file main.cpp.
padSize()
size_t osc::padSize (size_t size) inline
Definition at line 38 of file Bundle.cpp.
Referenced by osc::Message::deserialize(), osc::Value::deserialize(), osc::Bundle::serialize(), osc::Message::serialize(), and osc::Value::serialize().
Variable Documentation
MAX_BLOB_SIZE
size_t osc::MAX_BLOB_SIZE = 33554432 constexpr
Definition at line 29 of file Value.cpp.
Referenced by osc::Value::deserialize().
MAX_MESSAGE_SIZE
size_t osc::MAX_MESSAGE_SIZE = 16777216 constexpr
Definition at line 42 of file AddressImpl.h.
Referenced by osc::AddressImpl::send().